(
susvib: (
  directory: "Strings/Cello Section/susvib",
  samples: [
    (
      root: 36,
      layer: \v1,
      file: "susvib_C1_v1_1.wav",
      gain: 2.95,
    ),
    (
      root: 40,
      layer: \v1,
      file: "susvib_E1_v1_1.wav",
      gain: 7.27,
    ),
    (
      root: 43,
      layer: \v1,
      file: "susvib_G1_v1_1.wav",
      gain: 3.76,
    ),
    (
      root: 47,
      layer: \v1,
      file: "susvib_B1_v1_1.wav",
      gain: 3.79,
    ),
    (
      root: 50,
      layer: \v1,
      file: "susvib_D2_v1_1.wav",
      gain: 3.77,
    ),
    (
      root: 53,
      layer: \v1,
      file: "susvib_F2_v1_1.wav",
      gain: 5.95,
    ),
    (
      root: 57,
      layer: \v1,
      file: "susvib_A2_v1_1.wav",
      gain: 5.82,
    ),
    (
      root: 60,
      layer: \v1,
      file: "susvib_C3_v1_1.wav",
      gain: 5.11,
    ),
    (
      root: 64,
      layer: \v1,
      file: "susvib_E3_v1_1.wav",
      gain: 4.24,
    ),
    (
      root: 67,
      layer: \v1,
      file: "susvib_G3_v1_1.wav",
      gain: 4.47,
    ),
    (
      root: 71,
      layer: \v1,
      file: "susvib_B3_v1_1.wav",
      gain: 7.28,
    ),
    (
      root: 74,
      layer: \v1,
      file: "susvib_D4_v1_1.wav",
      gain: 6.80,
    ),
    (
      root: 77,
      layer: \v1,
      file: "susvib_F4_v1_1.wav",
      gain: 6.97,
    )
  ]
)
)
