(
susNV: (
  directory: "Woodwinds/Flute/susNV",

  samples: [
    (
      root: 60,
      layer: \v1,
      file: "LDFlute_susNV_C3_v1_1.wav",
      gain: 30.90
    ),
    (
      root: 64,
      layer: \v1,
      file: "LDFlute_susNV_E3_v1_1.wav",
      gain: 27.04
    ),
    (
      root: 69,
      layer: \v1,
      file: "LDFlute_susNV_A3_v1_1.wav",
      gain: 7.80
    ),
    (
      root: 72,
      layer: \v1,
      file: "LDFlute_susNV_C4_v1_1.wav",
      gain: 3.80
    ),
    (
      root: 76,
      layer: \v1,
      file: "LDFlute_susNV_E4_v1_1.wav",
      gain: 2.24
    ),
    (
      root: 81,
      layer: \v1,
      file: "LDFlute_susNV_A4_v1_1.wav",
      gain: 1.79
    ),
    (
      root: 84,
      layer: \v1,
      file: "LDFlute_susNV_C5_v1_1.wav",
      gain: 2.18
    ),
    (
      root: 88,
      layer: \v1,
      file: "LDFlute_susNV_E5_v1_1.wav",
      gain: 2.80
    )
  ]
)
)
