(
mf: (
  directory: "Strings/Harp",
  samples: [
    (
      root: 48,
      layer: \mf,
      file: "KSHarp_C3_mf.wav",
      gain: 31.70,
    ),
    (
      root: 52,
      layer: \mf,
      file: "KSHarp_E3_mf.wav",
      gain: 11.54,
    ),
    (
      root: 55,
      layer: \mf,
      file: "KSHarp_G3_mf.wav",
      gain: 7.56,
    ),
    (
      root: 59,
      layer: \mf,
      file: "KSHarp_B3_mf.wav",
      gain: 8.31,
    ),
    (
      root: 62,
      layer: \mf,
      file: "KSHarp_D4_mf.wav",
      gain: 5.30,
    ),
    (
      root: 65,
      layer: \mf,
      file: "KSHarp_F4_mf.wav",
      gain: 5.21,
    ),
    (
      root: 69,
      layer: \mf,
      file: "KSHarp_A4_mf.wav",
      gain: 3.05,
    ),
    (
      root: 72,
      layer: \mf,
      file: "KSHarp_C5_mf.wav",
      gain: 3.61,
    )
  ]
)
)
