(
var opening, answer, return, cadence;
opening = [
  (midinote: 50, dur: 2, dynamic: \mp),   // D3
  (midinote: 42, dur: 2, dynamic: \mp),   // F#2
  (midinote: 43, dur: 2, dynamic: \mp),   // G2
  (midinote: 42, dur: 2, dynamic: \mp)    // F#2
];
answer = [
  (midinote: 43, dur: 2, dynamic: \mp),   // G2
  (midinote: 45, dur: 2, dynamic: \mp),   // A2
  (midinote: 42, dur: 2, dynamic: \mp),   // F#2
  (midinote: 52, dur: 2, dynamic: \mp)    // E3
];
return = [
  (midinote: 50, dur: 2, dynamic: \mp),   // D3
  (midinote: 42, dur: 2, dynamic: \mp),   // F#2
  (midinote: 43, dur: 2, dynamic: \mp),   // G2
  (midinote: 42, dur: 2, dynamic: \mp)    // F#2
];
cadence = [
  (midinote: 43, dur: 2, dynamic: \mp),   // G2
  (midinote: 42, dur: 1, dynamic: \mp),   // F#2
  (midinote: 42, dur: 1, dynamic: \mp),   // F#2
  (midinote: 52, dur: 2, dynamic: \mp),   // E3
  (midinote: 52, dur: 2, dynamic: \mp)    // E3
];
[
  opening,
  answer,
  return,
  cadence
];
)
