(
var heldFs, upperAnswer, heldFsVar, climax;
heldFs = [
  (midinote: 50, dur: 2),   // D3
  (midinote: 52, dur: 2),   // E3
  (midinote: 42, dur: 2),   // F#2
  (midinote: 52, dur: 2)    // E3
];
upperAnswer = [
  (midinote: 43, dur: 2),   // G2
  (midinote: 45, dur: 2),   // A2
  (midinote: 50, dur: 2),   // D3
  (midinote: 52, dur: 2)    // E3
];
heldFsVar = [
  (midinote: 50, dur: 2),   // D3
  (midinote: 52, dur: 2),   // E3
  (midinote: 43, dur: 2),   // G2
  (midinote: 42, dur: 2)    // F#2
];
climax = [
  (midinote: 43, dur: 2),   // G2
  (midinote: 45, dur: 2),   // A2
  (midinote: 47, dur: 2),   // B2
  (midinote: 43, dur: 2)    // G2
];
[
  heldFs,
  upperAnswer,
  heldFsVar,
  climax
];
)
